services:
  db:
    image: postgres:16
    container_name: git-learning-platform-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: git_learning_platform
      POSTGRES_USER: git_user
      POSTGRES_PASSWORD: git_password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
